import 'dotenv/config';
import { Client, GatewayIntentBits, Collection } from 'discord.js';
import { loadEvents } from './handlers/eventHandler.js';
import { loadButtons } from './handlers/buttonHandler.js';
import { syncTickets } from './utils/ticketPoster.js';

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    GatewayIntentBits.GuildMembers,
  ],
});

// Attach collections to client so handlers can access them
client.buttons = new Collection();

await loadEvents(client);
await loadButtons(client);

client.login(process.env.DISCORD_TOKEN);

// ── Periodic ticket sync ─────────────────────────────────────────────────────
// After the initial sync in the ready event, poll the API every 10 seconds
// to pick up new tickets generated by the backend (e.g. after inventory updates).
const TICKET_TYPES = ['mpf', 'factory', 'resources', 'vehicles_structures'];
const POLL_INTERVAL_MS = 10_000;

client.once('ready', () => {
  setInterval(async () => {
    try {
      for (const type of TICKET_TYPES) {
        await syncTickets(client, type);
      }
    } catch (err) {
      console.error('[poll] periodic sync error:', err.message);
    }
  }, POLL_INTERVAL_MS);
  console.log(`[poll] ticket sync polling started (${POLL_INTERVAL_MS / 1000}s interval)`);
});